export { ReactComponent as CheckIcon } from './check.svg'
export { ReactComponent as SearchIcon } from './searchIcon.svg'

export { ReactComponent as CartIcon } from './cartIcon.svg'
export { ReactComponent as PersonIcon } from './personIcon.svg'
export { ReactComponent as LeftArrowIcon } from './leftArrowIcon.svg'
export { ReactComponent as RightArrowIcon } from './rightArrowIcon.svg'
export { ReactComponent as LeftIcon } from './leftIcon.svg'
export { ReactComponent as RightIcon } from './rightIcon.svg'

export { ReactComponent as HeartIcon } from './heartIcon.svg'
export { ReactComponent as RemoveIcon } from './removeInputIcon.svg'
export { ReactComponent as TruckIcon } from './truckIcon.svg'
export { ReactComponent as SettingIcon } from './settingIcon.svg'
export { ReactComponent as AnnouncementIcon } from './announcementIcon.svg'
export { ReactComponent as LightModeIcon } from './lightModeIcon.svg'
export { ReactComponent as DarkModeIcon } from './darkModeIcon.svg'
export { ReactComponent as NoImageIcon } from './noImageIcon.svg'
export { ReactComponent as BookIcon } from './bookIcon.svg'
export { ReactComponent as CloseIcon } from './closeIcon.svg'
export { ReactComponent as EyeIcon } from './eyeIcon.svg'
export { ReactComponent as PlusIcon } from './plusIcon.svg'
export { ReactComponent as BookmarkIcon } from './bookmarkIcon.svg'

export { ReactComponent as StarIcon } from './starIcon.svg'
export { ReactComponent as ReadingIcon } from './readingIcon.svg'
export { ReactComponent as WantToReadIcon } from './wantToReadIcon.svg'
export { ReactComponent as GithubIcon } from './githubIcon.svg'
export { ReactComponent as MenuIcon } from './menuIcon.svg'
